### ISSUE TITLE
Status of this codebase?

### ISSUE THREAD

**Issue by pospi** [holochain-open-dev/holochain-time-index#8]
Hi there (: Just wanted to check in and see if this module is considered to have a stable API yet.
Also curious whether it has been adapted to the new `PathEntry` changes that recently landed in core. Thanks!

**Comment by jdeepee** [comment]
Hey @pospi ! I would not call this library stable yet unfortunately, the `get_links_and_load_for_time_span()` & `get_links_for_time_span` & `index_entry()` functions will likely remain the same, but I cannot say the same for the data structure or other functions. 

Yes it has the new `PathEntry` changes and is in-line with hdk version 123.

As for the stability of usage of this crate; it is working well for our descending & ascending link querying inside Flux, there is likely a few bugs lying around and performance optimisations to be made, but mostly working!
