### ISSUE TITLE
Elaborate on documentation for rate limiting & DHT tree structure

### ISSUE THREAD

**Issue by pospi** [holochain-open-dev/holochain-time-index#9]
`enforce_spam_limit` and `max_chunk_interval` aren't immediately intuitive to me. The default configuration Junto is using in Flux is-

```js
"enforce_spam_limit": 20,
"max_chunk_interval": 43200000,
```

Does this mean a rate limiting of max 20 entries per agent per DNA every 43,200,000µs (43.2s); or something else? Basically I want to know how to calculate my max bucket size based on the configuration variables.

**Comment by jdeepee** [comment]
Yeah your interpretation is correct. With those values, if I indexed an entry now, the index tree that gets created looks something like:

```
2022 -> 06 -> 09 -> Index { from: 1654776000s, until: 1654819200s } -> IndexedEntry
```

The `enforce_spam_limit` value is not currently being used. My idea was that it would be used to enforce a max number entries an agent can add to each individual `Index { }`. Although with the new rate limiting additions coming to the HDK, I guess this is not really useful anymore.

**Comment by jdeepee** [comment]
I think even the `max_chunk_interval ` may be a bit overkill and just indexing on the time tree with some defined depth is enough. It mainly just provides a way to index with greater fidelity and thus reduce the number of entries that would be linked from a given time path.

**Comment by pospi** [comment]
Alright, sweet. Well, we're not that fussed about performance tweaks at the moment but will keep watching this library for such an update as it becomes relevant (:
